### ISSUE TITLE
practice

### ISSUE THREAD

**Issue by FridaPshitik** [skyvar/self-learning#10]

**Comment by FridaPshitik** [comment]
asdf #8

**Comment by FridaPshitik** [comment]
> asdf #8

**Comment by FridaPshitik** [comment]
> _No description provided._

**Comment by bdsoha** [comment]
> ok

Use *reaction* icons to indicate that you *acknowledge* something as mentioned [here](https://github.com/skyvar/self-learning/issues/9#issuecomment-1475953250)
