### ISSUE TITLE
Research Git Branching Commands

### ISSUE THREAD

**Issue by EsterWeiss** [skyvar/self-learning#2]
## Description
Research the various *`git` commands* and making the most correct use of them.

**Comment by bdsoha** [comment]
- Where is the description?
- What is the issue's title?

**Comment by RivkaZishinski** [comment]
# Description
Investigating the topics and making the most correct use of the topic-Git Branching Commands

**Comment by bdsoha** [comment]
> # Description
> Investigating the topics and making the most correct use of the topic-Git Branching Commands

The description is at the top of the page, change it [here](https://github.com/skyvar/self-learning/issues/2#issue-1631693414).

**Comment by bdsoha** [comment]
> we (RivkaZishinski and EsterWeiss )are working on one computer(EsterWeiss) -does it good?

If you are asking whether you should be using 1 or 2 computers: it is up to you.

**Comment by bdsoha** [comment]
My mistake, this has already been taken #1

**Comment by EsterWeiss** [comment]
its our task?

**Comment by bdsoha** [comment]
> its our task?

Yes, I was confused between the names of the issues. Sorry 😉

**Comment by EsterWeiss** [comment]
In order to experiment with the commands, we ask for permission to create a fork without destroying the original code, of course at the end of the process we will delete the fork

**Comment by bdsoha** [comment]
> In order to experiment with the commands, we ask for permission to create a fork without destroying the original code, of course at the end of the process we will delete the fork

You can create a private repo on your personal account.

**Comment by bdsoha** [comment]
@EsterWeiss You can also make a `feature/***` branch.
If the naming is incorrect, it will be deleted.

**Comment by EsterWeiss** [comment]
thank
We received the first recommendation

**Comment by bdsoha** [comment]
Yes, thanks for catching that mistake.

**Comment by bdsoha** [comment]
Any questions? Updates?

**Comment by RivkaZishinski** [comment]
Now we started working because until now the electricity was not working.

**Comment by bdsoha** [comment]
Good comment 👍.
You are only expected to provide alternatives when available.
There are many cases that do not have an alternative.

**Comment by RivkaZishinski** [comment]
We need to explore its main 3 from scratch git or the differences between `git reset` and `git revert` ?

**Comment by bdsoha** [comment]
> We need to explore its main 3 from scratch git or the differences between `git reset` and `git revert` ?

Can you elaborate? I didn't fully understand.

**Comment by RivkaZishinski** [comment]
The `reset `command has three levels: --soft --mixed -- hard
There are articles that talk about `reset `in general and some that detail the three levels. Should I submit a detailed or abbreviated explanation in the document?

**Comment by bdsoha** [comment]
> The `reset `command has three levels: --soft --mixed -- hard There are articles that talk about `reset `in general and some that detail the three levels. Should I submit a detailed or abbreviated explanation in the document?

A short explanation of each should suffice.
The main goal is for you and your colleagues to understand when and why each should be used. If the description is *too* long, they may get lost. On the other hand, if it is *too* short, they wont understand.

**Comment by RivkaZishinski** [comment]
We uploaded a folder with some of the topics to our branch : merge ,merge squash ,commit ,checkout

**Comment by bdsoha** [comment]
> We uploaded a folder with some of the topics to our branch : `merge `,`merge squash `,`commit `,`checkout`

Where?

**Comment by RivkaZishinski** [comment]
in our branch : feature/research-git-branching-commands

**Comment by bdsoha** [comment]
> in our branch : feature/research-git-branching-commands

Please create a PR.
**Make sure to link this issue to the PR and add a meaningful description.**

**Comment by bdsoha** [comment]
@RivkaZishinski Is this complete? Has someone reviewed it?

**Comment by bdsoha** [comment]
Is there a linked PR?
When that PR is **approved** and merged, this issue will automatically close.
