### ISSUE TITLE
Research Various Branching Workflows

### ISSUE THREAD

**Issue by chananaimen** [skyvar/self-learning#6]
Research the various branching workflows and different ways of using them.

**Comment by bdsoha** [comment]
@RivkaBerlinski Please change your profile name to use title-case *(i.e. `Rivka Berlinski`)*.

**Comment by bdsoha** [comment]
Any questions? Updates?

**Comment by RivkaBerlinski** [comment]
Is it necessary to specify handling of conflicts as part of workflows in a markup-based presentation
Or simply focus on the general work processes?
