### ISSUE TITLE
Research GitHub Workflow Tooling

### ISSUE THREAD

**Issue by FridaPshitik** [skyvar/self-learning#9]
Research GitHub's workflow tooling, such as:

- Issues
- Project
- PR
- Discussions
- Milestones 
- Labels

**Comment by bdsoha** [comment]
- Where is the description?

**Comment by FridaPshitik** [comment]
Provide details of workflow in GItHub
 in topics:  issues, project, PR features, discussions, milestones and labels.

**Comment by bdsoha** [comment]
The **description** is at the top of the page, change it [here](https://github.com/skyvar/self-learning/issues/9#issue-1631744704).

**Comment by bdsoha** [comment]
> Provide details of workflow in GItHub in topics: issues, project, PR features, discussions, milestones and labels.

The **description** is at the top of the page, change it [here](https://github.com/skyvar/self-learning/issues/9#issue-1631744704).

**Comment by FridaPshitik** [comment]
done

**Comment by bdsoha** [comment]
> done

Use *reaction* icons to indicate that you *acknowledge* something.

**Comment by bdsoha** [comment]
@FridaPshitik Please change your profile name to use title-case *(i.e. `Frida Pshitik`)*.

**Comment by bdsoha** [comment]
@chanaSlumianski  Please change your profile name to use title-case *(i.e. `Chana Slumianski`)*.

**Comment by FridaPshitik** [comment]
we want make sure if we must look for alternative of every point in out task?

**Comment by bdsoha** [comment]
> we want make sure if we must look for alternative of every point in out task?

Good question. You can skip the following alternatives:
- PR
- Labels
- Milestones

**Comment by bdsoha** [comment]
Any questions? Updates?

**Comment by bdsoha** [comment]
### Hint

When researching *projects*, pay attention to the fact that there are *organization-level projects* and *repo-level projects*.
They play different business and management roles.

**Comment by SaraLitman** [comment]
I did it thanks

**Comment by bdsoha** [comment]
> I did it thanks

@SaraLitman This is not your *issue*.

**Comment by FridaPshitik** [comment]
we can divide our README to few files by topics?
And if so we can name the file like the topic in this file?

**Comment by FridaPshitik** [comment]
we finish .
we want to know if it's ok.

**Comment by bdsoha** [comment]
Open a PR.
